# This file was generated by GoReleaser. DO NOT EDIT.
class Zpm < Formula
  desc "Simple and fast zsh plugins manager"
  homepage "https://github.com/eugene-babichenko/zpm"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/eugene-babichenko/zpm/releases/download/v0.2.1/zpm_0.2.1_macOS_amd64.tar.gz"
    sha256 "3f417f49dfd479da2f4eddbb87083ae09ac6387c24136259e4f5caa3d0d8c448"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/eugene-babichenko/zpm/releases/download/v0.2.1/zpm_0.2.1_linux_amd64.tar.gz"
      sha256 "14a37f1216a4361aab77cb3bf2023a46fae33fc69f279b89a46216148dedbc20"
    end
  end

  def install
    bin.install "zpm"
  end
end
